// src/Climbers/ClimbersTable.svelte
<script lang="ts">
    import { climbers } from "../stores.js";
    import type Climber from "../climber.js";
    import ClimberLine from "./ClimberLine.svelte";
    import { jsPDF } from "jspdf";
    import autoTable from "jspdf-autotable";
    import { onDestroy, onMount } from "svelte";

    let manager: string;

    onMount(() => {
        manager = localStorage.getItem("manager") || "";
    });

    function exportList(event) {
        event.target.setAttribute("disabled", true);

        localStorage.setItem("manager", manager);

        const doc = new jsPDF("landscape");

        const columns = [
            {header:"NOM Prénom", dataKey: "table-name"},
            {header:"N° de licence", dataKey: "table-id"},
            {header:"Année de validité", dataKey: "table-year"},
            {header:"Club", dataKey: "table-club"},
            {header:"Date de naissance", dataKey: "table-birthdate"},
            {header:"Passeport", dataKey: "table-passport"},
        ];

        doc.text("Liste des grimpeurs à la séance du " + new Date().toLocaleString(), 15, 10);
        doc.text("Responsable : " + manager, 281, 10, {align: "right"});
        autoTable(doc, { html: "#climbers-table", columns: columns, theme: "grid" });
        doc.save("export.pdf");

        event.target.removeAttribute("disabled");
    }
</script>

<style>
    .table-container {
        overflow-x: auto;
        max-width: 90vw;
    }

    .big-button {
        display: block;
        width: 100%;
        padding: 0.8rem;
    }

    form {
        margin-top: 16px;
        display: flex;
        flex-direction: column;
        gap: 0.6rem;
    }
</style>

<div class="table-container">
    <table id="climbers-table">
        <thead>
            <tr>
                <th id="table-date">Heure du scan</th>
                <th id="table-name">NOM Prénom</th>
                <th id="table-id">N° de licence</th>
                <th id="table-year">Année de validité</th>
                <th id="table-club">Club</th>
                <th id="table-birthdate">Date de naissance</th>
                <th id="table-passport">Passeport</th>
                <th><button class="icon" on:click={() => climbers.clear()}>🧹&nbsp;Tout effacer</button></th>
            </tr>
        </thead>

        <tbody>
            {#each $climbers as climber}
            <ClimberLine climber={climber}>
                <button class="icon" on:click={() => climbers.delClimber(climber)}>❌&nbsp;Supprimer</button>
            </ClimberLine>
            {/each}
        </tbody>

        <tfoot style="display: none;">
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>Total : {$climbers.length}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>

<form on:submit|preventDefault={exportList}>
    <div>
        <label for="manager">Responsable: </label>
        <input bind:value={manager} required id="manager" type="text">
    </div>

    <button type="submit" class="big-button">Exporter la liste</button>
</form>

// src/app/climbers-table/climbers-table.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import Climber from 'src/app/climber';

@Component({
  selector: 'app-climbers-table',
  templateUrl: './climbers-table.component.html',
  styleUrls: ['./climbers-table.component.css']
})
export class ClimbersTableComponent implements OnInit {
  manager = "";
  @Input() climbers!: Climber[];

  ngOnInit(): void {
    this.manager = localStorage.getItem("manager") || "";
  }

  resetClimbersList(): void {
    this.climbers = [];
  }

  deleteClimberFromList(climber: Climber): void {
    this.climbers.splice(this.climbers.indexOf(climber), 1);
    console.log(this.climbers);
  }

  exportTable(event: Event): void {
    event.preventDefault();
    console.log(event);

    const date = new Date();
    const nomFichier = `perm_${date.getFullYear()}-${date.getMonth()}-${date.getDay()}.pdf`;

    // Bouton du formulaire indisponible...
    // event.target.setAttribute("disabled", true);
    document?.getElementById("exportButton")?.toggleAttribute('disabled', true);

    // Sauvegarde du nom du responsable
    localStorage.setItem("manager", this.manager);

    // Création du document PDF
    const doc = new jsPDF("landscape");
    const columns = [
      { header: "NOM Prénom", dataKey: "table-name" },
      { header: "N° de licence", dataKey: "table-id" },
      { header: "Année de validité", dataKey: "table-year" },
      { header: "Club", dataKey: "table-club" },
      { header: "Date de naissance", dataKey: "table-birthdate" },
      { header: "Passeport", dataKey: "table-passport" },
    ];
    doc.text(`Liste des grimpeurs à la séance du ${date.toLocaleString()}`, 15, 10);
    doc.text(`Responsable : ${this.manager}`, 281, 10, { align: "right" });
    autoTable(doc, { html: "#climbers-table", columns: columns, theme: "grid" });
    doc.save(nomFichier);

    // Bouton du formulaire dispo
    document?.getElementById("exportButton")?.toggleAttribute('disabled', false);
  }

}

<div class="table-container">
    <table id="climbers-table">
        <thead>
            <tr>
                <th id="table-date">Heure du scan</th>
                <th id="table-name">NOM Prénom</th>
                <th id="table-id">N° de licence</th>
                <th id="table-year">Année de validité</th>
                <th id="table-club">Club</th>
                <th id="table-birthdate">Date de naissance</th>
                <th id="table-passport">Passeport</th>
                <th>🗑</th>
            </tr>
        </thead>

        <tbody>
            <tr *ngFor="let climber of climbers">
                <!--
                    <th>Nom</th>
                    <th>N° de licence</th>
                    <th>Année de validité</th>
                    <th>Club</th>
                    <th>Année de naissance</th>
                    <th>Passeport</th>
                    <th>/* Boutons */</th>
                 -->

                <td>{{climber.scanTime | date:'dd/MM/yyyy HH:mm' }}</td>
                <td>{{climber.name}}</td>
                <td>{{climber.id}}</td>
                <td [class.invalid]="!climber.isLicenceValid()">{{ climber.year }}</td>
                <td>{{climber.club ? climber.club : "?"}}</td>
                <td [class.kid]="!climber.isClimberAdult()">{{climber.birthDate}}</td>
                <td>
                    <span [class.special]="climber.getHighestPassport().special"
                        [style.background]="climber.getHighestPassport().color"></span>
                    &nbsp;{{ climber.getHighestPassport().shortname }}
                </td>
                <td>
                    <button class="icon" (click)="deleteClimberFromList(climber)">❌</button>
                </td>
            </tr>
        </tbody>

        <tfoot>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th *ngIf="climbers.length>0">Total : {{climbers.length}}</th>
            </tr>
        </tfoot>
    </table>
</div>

<form *ngIf="climbers.length>0" (submit)="exportTable($event)">
    <div>
        <label for="manager">Responsable: </label>
        <input [(ngModel)]="manager" required name="manager" type="text">
    </div>

    <div class="controls horizontal">
        <button class="danger" (click)="resetClimbersList()">Tout effacer</button>
        <button id="exportButton" type="submit">Exporter la liste</button>
    </div>
</form>
