// src/LicenceDisplay.svelte
<script lang="ts">
  import type Climber from "./climber";

  export let licence: Climber;
</script>

<style>
ul { margin :0; }
.profile-picture {
  float: right;
  max-width: 6rem;
}
</style>

<h2>Dernier scan</h2>
{#if licence}
  {#if licence.picture}
    <img class="profile-picture" src={licence.picture} alt="{licence.name}">
  {/if}

  <b>{licence.name} <small>{licence.id}</small></b>

  {#if !licence.isLicenceValid()}
    <div class="problem">La licence n'a pas été renouvellée !</div>
  {/if}


  <dl>
    <dt>Date de naissance</dt>
    <dd>{licence.birthDate}{ !licence.isClimberAdult() ? " 👶" : ""}</dd>
  </dl>
  {#if licence.club}
  <dl>
    <dt>Club</dt>
    <dd>{licence.club}</dd>
  </dl>
  {/if}
  <dl>
    <dt>Diplômes</dt>
    <dd>
      <ul>
        {#each licence.diplomas as diploma}
          <li>{diploma}</li>
        {/each}
      </ul>
    </dd>
  </dl>
{/if}

// src/app/licence-display/licence-display.component.ts
import { Component, Input, OnInit } from '@angular/core';
import Climber from '../climber';

@Component({
  selector: 'app-licence-display',
  templateUrl: './licence-display.component.html',
  styleUrls: ['./licence-display.component.css']
})
export class LicenceDisplayComponent implements OnInit {
  @Input() climber!: Climber;

  constructor() { }

  ngOnInit(): void {
  }

}

<img *ngIf="climber.picture" class="profile-picture" src={{climber.picture}} alt="{{climber.name}}">

<b>{{climber.name}} <small>{{climber.id}}</small></b>

<div *ngIf="!climber.isLicenceValid()" class="problem">La licence n'a pas été renouvellée !</div>

<dl>
    <dt>Date de naissance</dt>
    <dd>{{climber.birthDate}}{{ !climber.isClimberAdult() ? " 👶" : ""}}</dd>
</dl>

<dl *ngIf="climber.club">
    <dt>Club</dt>
    <dd>{{climber.club}}</dd>
</dl>

<dl>
    <dt>Diplômes</dt>
    <dd>
        <ul>
            <li *ngFor="let diploma of climber.diplomas">{{diploma}}</li>
        </ul>
    </dd>
</dl>
