// src/app/app.component.ts
import { Component } from '@angular/core';
import Climber from './climber';
import { ClimbersService } from './climbers.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  climbers: Climber[] = [];
  lastScannedClimber: Climber | undefined;

  constructor(private climbersService: ClimbersService) { }

  ngOnInit() {
    this.climbers = this.climbersService.getClimbers();
    this.lastScannedClimber = this.climbers[this.climbers.length - 1];
  }

  scannedURLHandler(url: string): void {
    this.climbersService.addClimberFromURL(url);
  }
}

<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Scanner FFME</title>
</head>

<body>
    <header class="panel full-width">
        <h1>Scanner de licences FFME</h1>
    </header>

    <main class="wrapper">
        <div class="panel box">
            <app-scanner (scannedURL)=scannedURLHandler($event)></app-scanner>
        </div>

        <div class="panel box">
            <h2>Dernier scan</h2>

            <app-licence-display *ngIf=(lastScannedClimber) [climber]="lastScannedClimber"></app-licence-display>
        </div>

        <div class="panel box full-width">
            <app-climbers-table [climbers]="climbers"></app-climbers-table>
        </div>
    </main>

    <footer>
        <p>Appli web réalisée par <a href="https://github.com/VincentPloquien">Vincent Ploquien</a> pour l'<a
                href="https://asaescalade.fr/">ASA Escalade</a>.</p>
        <p>Le code est disponible sur <a href="https://github.com/VincentPloquien/Scanner-Licence-FFME">Github</a> !</p>
    </footer>

</body>

</html>

// src/App.svelte
<script lang="ts">
  import Climber from "./climber";
  import ClimbersTable from "./Climbers/ClimbersTable.svelte";
  import DisplayLicence from "./LicenceDisplay.svelte";
  import Scanner from "./LicenceScanner.svelte";
  import { climbers } from "./stores";


  let currentClimber : Climber = null;

  function parseLicenceFromHTML(doc: Document) {
    return new Climber(
      doc.querySelector("#box1 > h1").textContent.trim(),
      parseInt(doc.querySelector("#box1 > p > span").textContent.trim()),
      (doc.querySelector("#box1 > img") as HTMLImageElement)?.src.replace("http://", "https://"),
      doc.querySelector("#box1 > p > b:nth-child(4)")?.nextSibling?.textContent.trim(),
      doc.querySelector("#box > p:nth-child(4) > b:nth-child(1)")?.nextSibling?.textContent.replace(new RegExp(/\(.*\)/, "g"), "").trim(),
      parseInt(doc.querySelector("#box > p:nth-child(4) > b:nth-child(3)")?.nextSibling.textContent.trim()),
      doc.querySelector("#box > p:nth-child(4) > b:nth-child(5)")?.nextSibling.textContent.trim(),
      Array.from(doc.querySelectorAll("#box > ul > li")).map((node: HTMLElement) => node.innerText.trim()),
      doc.querySelector("#box > p:nth-child(8) > b")?.nextSibling?.textContent.trim(),
      Date.now()
    );
  }

  async function fetchLicence(url: string): Promise<Climber> {
    var request_url = url.replace("licencie.ffme.fr", "asa.akwaryoum.fr/ffme");

    return await fetch(request_url)
      .then((response) => response.arrayBuffer())
      .then((buffer) => {
        // iso-8859-1 decoding from https://schneide.blog/2018/08/08/decoding-non-utf8-server-responses-using-the-fetch-api/
        let decoder = new TextDecoder("iso-8859-1");
        let text = decoder.decode(buffer);
        return text;
      })
      .then((html) => {
        // parse the interesting bits from the FFME page
        var parser = new DOMParser();
        var doc = parser.parseFromString(html, "text/html");

        var licence: Climber = parseLicenceFromHTML(doc);

        return licence;
      })
      .then((licence) => {
        console.debug("Decoded licence: ", licence);
        return licence;
      })
      .catch((error) => {
        console.error("Impossible de récupérer la licence: " + error);
        return null;
      });
  }

  async function handleScan(event: any) {
    let url = event.detail.result;
    let licence = await fetchLicence(url);

    if (licence) {
      currentClimber = licence;

      climbers.addClimber(licence);
    }
  }
</script>

<header class="panel full-width">
  <h1>Scanner de licences FFME</h1>
</header>

<main class="wrapper">
  <div class="panel box">
    <Scanner on:result={handleScan} />
  </div>

  <div class="panel box">
    <DisplayLicence bind:licence={currentClimber} />
  </div>


  {#if $climbers.length > 0}
    <div class="panel box full-width">
      <ClimbersTable />
    </div>
  {/if}
</main>

<footer>
  <p>Appli web réalisée par <a href="https://github.com/VincentPloquien">Vincent Ploquien</a> pour l'<a href="https://asaescalade.fr/">ASA Escalade</a>.</p>
  <p>Le code est disponible sur <a href="https://github.com/VincentPloquien/Scanner-Licence-FFME">Github</a> !</p>
</footer>
